<a href="https://colab.research.google.com/github/itsTurner/ben-learns-ml/blob/main/GaussianHumidityPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If runtime ends then reimport

##Setting everything up

Import numpy and pandas

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import math



Open csv file with Pandas and format into arrays

In [ ]:
fullWeatherData = pd.read_csv('austin_weather.csv')
weatherData = fullWeatherData[['TempAvgF', 'DewPointAvgF', 'HumidityAvgPercent']]
shuffledWeatherData = weatherData.sample(frac=1)
X_train, X_test, y_train, y_test = train_test_split(shuffledWeatherData[['TempAvgF', 'DewPointAvgF']], shuffledWeatherData[['HumidityAvgPercent']], test_size=0.1, random_state=42)
X_trainArrayTemp = np.array(X_train['TempAvgF'])
X_trainArrayDew = np.array(X_train['DewPointAvgF'])
X_testArrayTemp = np.array(X_test['TempAvgF'])
X_testArrayDew = np.array(X_test['DewPointAvgF'])
y_trainArray = np.array(y_train['HumidityAvgPercent'])
y_testArray = np.array(y_test['HumidityAvgPercent'])
print(X_trainArrayTemp)
print(X_trainArrayDew)
print(X_testArrayTemp)
print(X_testArrayDew)
print(y_trainArray)
print(y_testArray)


[85 73 48 ... 83 70 89]
[68 61 36 ... 70 63 72]
[81 85 79 74 87 85 55 84 39 88 73 51 88 66 71 75 86 69 44 71 82 86 79 80
 78 87 70 59 72 74 80 87 62 73 84 69 60 76 51 85 74 68 89 40 89 81 74 45
 67 63 90 64 91 62 58 46 77 55 76 84 55 63 82 88 60 69 71 84 73 41 78 53
 84 50 75 61 66 73 76 34 83 57 64 86 80 91 91 79 84 69 79 54 89 63 60 53
 32 67 49 52 54 47 85 65 87 70 85 89 83 85 78 90 83 81 89 59 84 70 82 84
 75 74 63 86 83 69 82 65 56 88 45 91]
[73 75 71 66 70 70 47 72 33 70 64 49 70 55 68 59 71 61 37 65 72 72 56 74
 75 72 67 51 63 60 58 72 37 66 72 54 41 65 45 74 72 66 71 26 67 65 66 32
 66 53 71 43 73 47 22 36 66 46 62 72 36 56 67 71 28 62 63 67 61 30 50 41
 74 42 67 55 54 59 67 31 63 45 55 76 57 73 69 73 69 58 72 38 70 46 46 32
 12 56 25 23 40 45 71 58 64 65 72 74 70 68 71 71 75 62 68 36 72 64 63 71
 62 63 58 71 72 54 71 51 45 71 35 70]
[62 72 70 ... 67 82 63]
[78 76 78 78 62 66 89 72 83 61 72 95 62 62 86 56 65 84 75 82 75 70 55 85
 90 67 92 75 68 69 59 65 52 76 72 62 53 66 79 72 

##Process Data 
Sort Data, Get Mean, and get variance

Yes this might be easier to do but this was written at 11:00 PM and I no longer understand it

In [ ]:
twentiesSet = []
thirtiesSet = []
fourtiesSet = []
fiftiesSet = []
sixtiesSet = []
seventiesSet = []
eightiesSet = []
ninetiesSet = []
for i in range(len(y_trainArray)):
  if y_trainArray[i] > 19 and y_trainArray[i] <=29:
    twentiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 29 and y_trainArray[i] <=39:
    thirtiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 39 and y_trainArray[i] <=49:
    fourtiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 49 and y_trainArray[i] <=59:
    fiftiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 59 and y_trainArray[i] <=69:
    sixtiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 69 and y_trainArray[i] <=79:
    seventiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 79 and y_trainArray[i] <=89:
    eightiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  elif  y_trainArray[i] > 89 and y_trainArray[i] <=99:
    ninetiesSet.append([X_trainArrayTemp[i], X_trainArrayDew[i], y_trainArray[i]])
  else:
    print(y_trainArray[i])
sortedSet = [twentiesSet, thirtiesSet, fourtiesSet, fiftiesSet, sixtiesSet, seventiesSet, eightiesSet, ninetiesSet]
# print(twentiesSet)
# print(thirtiesSet)
# print(fourtiesSet)
# print(fiftiesSet)
# print(sixtiesSet)
# print(seventiesSet)
# print(eightiesSet)
# print(ninetiesSet)
# print(sortedSet)

def mean(data, local):
  sum = 0
  for i in data:
    sum+=i[local]
  return sum/len(data)

meanArray = []
for i in range(len(sortedSet)):
  #print(i)

  meanArray.append([mean(sortedSet[i], 0), mean(sortedSet[i], 1)])

def variance(data, local, mean):
  #print("This is the mean", mean[local])
  sum = 0
  for i in data:
    sum += (i[local] - mean[local])**2
  return sum/(len(data))
varianceArray = []

for i in range(len(sortedSet)):
  #print(i)
  varianceArray.append([variance(sortedSet[i], 0, meanArray[i]), variance(sortedSet[i], 1, meanArray[i])])
  #print(sortedSet[i])

for i in sortedSet:
  print(i)

for i in range(len(varianceArray)):
  print("Mean array", meanArray[i])
  print("Variance array",varianceArray[i])
  

  #print(mean(sortedSet[i], 0))

[[62, 27, 28], [76, 37, 27], [76, 35, 27]]
[[78, 41, 36], [64, 36, 36], [66, 33, 32], [56, 20, 37], [51, 23, 39], [59, 30, 37], [71, 35, 33], [72, 34, 36], [67, 35, 31], [63, 33, 35], [52, 23, 38], [62, 34, 38], [63, 30, 38], [68, 37, 36], [59, 30, 39], [56, 27, 38], [56, 31, 39], [55, 26, 36], [52, 25, 39], [70, 35, 33], [80, 39, 39], [65, 33, 39], [52, 26, 35], [54, 20, 31]]
[[33, 14, 48], [54, 33, 45], [61, 36, 44], [38, 17, 44], [74, 43, 40], [59, 36, 48], [54, 28, 42], [57, 43, 46], [65, 44, 43], [64, 40, 43], [55, 34, 47], [66, 43, 49], [61, 37, 48], [83, 57, 45], [64, 39, 45], [69, 46, 48], [41, 24, 48], [76, 52, 45], [64, 36, 44], [69, 45, 48], [60, 38, 48], [73, 50, 48], [93, 68, 48], [75, 48, 46], [79, 45, 45], [72, 43, 40], [86, 61, 47], [32, 11, 48], [55, 30, 44], [55, 33, 45], [30, 12, 48], [53, 29, 42], [47, 20, 40], [68, 46, 48], [50, 27, 46], [56, 29, 45], [70, 43, 43], [70, 50, 48], [43, 22, 49], [92, 68, 43], [70, 45, 46], [47, 23, 49], [57, 27, 40], [57, 32, 41], [63

##Obtain Probability
Probability Function

In [ ]:
# def probabilityArrayFunc(data, mean, variance):
#   probabilityArray = []
#   for i in data:
#     probabilityArray.append((1/(math.sqrt(2*math.pi*variance)))*math.exp(-1*((mean-i)**2)/(2*variance)))
#   return probabilityArray
exampleArray = []
def probabilityArrayFunc(data, mean, variance):
  probArray = []
  for i in range(len(data)):
    probArray.append((1/(math.sqrt(2*math.pi*variance[i])))*math.exp(-1*((mean[i]-data[i])**2)/(2*variance[i])))
  return probArray

#first iterate over ever section mean and variance and calculate probabilities like that
#then move forward through data and calculate probabilities of the set
X_testPrediction = []

for j in range(len(X_testArrayDew)):
  tempArray = []
  for i in range(len(meanArray)):
    try:
      tempArray.append(np.log(probabilityArrayFunc([X_testArrayTemp[j], X_testArrayDew[j]], [meanArray[i][0], meanArray[i][1]], [varianceArray[i][0], varianceArray[i][1]])))
      #break
    except ValueError:
      print("Well this one had 0")      
    #print(np.log(probabilityArrayFunc([X_testArrayTemp[j], X_testArrayDew[j]], [meanArray[i][0], meanArray[i][1]], [varianceArray[i][0], varianceArray[i][1]])))
  X_testPrediction.append(tempArray)
for i in X_testPrediction:
  print(i)
#print(X_testPrediction)


#print(probabilityArrayFunc([X_trainArrayTemp[0], X_trainArrayDew[0]], [meanArray[0][0], meanArray[0][1]], [varianceArray[0][0], varianceArray[0][1]]))

#probabilityArrayFunc([X_trainArrayTemp, X_trainArrayDew], )


  #print(sortedSet[i])
# print(probabilityArrayFunc(X_trainArrayTemp, X_trainArrayTempMean, X_trainArrayTempVariance))
# print(probabilityArrayFunc(X_trainArrayDew, X_trainArrayDewMean, X_trainArrayDewVariance))
#print(probabilityArrayFunc(y_trainArray, y_trainArrayMean, y_trainArrayVariance))

[array([ -3.87866125, -45.23945109]), array([ -5.72303957, -30.3934455 ]), array([-4.57491515, -7.28631323]), array([-4.01461787, -5.02789111]), array([-3.6223517 , -3.96377931]), array([-3.60894593, -3.7594473 ]), array([-4.25588068, -3.95961719]), array([-5.18318834, -4.42268889])]
[array([ -4.95008982, -49.63230823]), array([ -6.9941091 , -33.07616261]), array([-5.00938579, -7.71267226]), array([-4.2623617 , -5.26556693]), array([-3.79421273, -4.13462783]), array([-3.93241092, -3.97001361]), array([-4.78740305, -4.18446764]), array([-5.89086752, -4.69918329])]
[array([ -3.48070206, -41.06087966]), array([ -5.17883914, -27.8345461 ]), array([-4.38707471, -6.88271555]), array([-3.91547065, -4.80861898]), array([-3.5689719 , -3.81779789]), array([-3.49452853, -3.58586622]), array([-4.036109  , -3.76818462]), array([-4.87315422, -4.17764755])]
[array([ -2.88758982, -31.55195109]), array([ -4.08472989, -21.9790001 ]), array([-4.00320867, -5.97330229]), array([-3.73971624, -4.34095481]), 

Predictions for humidity

In [ ]:
def occurences(data, toSearch):
  amountIn = 0
  for i in data:
    if i == toSearch:
      amountIn+=1
  return amountIn/len(data)
twenty = []
thirty = []
fourty = []
fifty = []
sixty = []
seventy = []
eighty = []
ninety = []
occurenceArray = []
for i in range(10):
  for j in range(10):
    if i == 2:
      twenty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 3:
      thirty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 4:
      fourty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 5:
      fifty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 6:
      sixty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 7:
      seventy.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 8:
      eighty.append(occurences(y_trainArray, (i*10 + j)))
    elif i == 9:
      ninety.append(occurences(y_trainArray, (i*10 + j)))
totalTwenty = 0
totalThirty = 0
totalFourty = 0
totalFifty = 0
totalSixty = 0
totalSeventy = 0
totalEighty = 0
totalNinety = 0
for i in twenty:
  totalTwenty+=i
totalTwenty = np.log(totalTwenty)
for i in thirty:
  totalThirty+=i
totalThirty = np.log(totalThirty)
for i in fourty:
  totalFourty+=i
totalFourty = np.log(totalFourty)
for i in fifty:
  totalFifty+=i
totalFifty = np.log(totalFifty)
for i in sixty:
  totalSixty+=i
totalSixty = np.log(totalSixty)
for i in seventy:
  totalSeventy+=i
totalSeventy = np.log(totalSeventy)
for i in eighty:
  totalEighty+=i
totalEighty = np.log(totalEighty)
for i in ninety:
  totalNinety+=i
totalNinety = np.log(totalNinety)

occurenceArray.append(totalTwenty)
occurenceArray.append(totalThirty)
occurenceArray.append(totalFourty)
occurenceArray.append(totalFifty)
occurenceArray.append(totalSixty)
occurenceArray.append(totalSeventy)
occurenceArray.append(totalEighty)
occurenceArray.append(totalNinety)

for i in occurenceArray:
  print(i)



-5.973809611869261
-3.8943680701894254
-2.665702653273118
-1.7791170758128787
-1.11658453107254
-1.2855245191706632
-2.3188317094310062
-3.3112217848438084


Final Step to Calculate what stuff should be

In [ ]:
correct = 0
close = 0
kindaClose = 0
for i in range(len(X_testPrediction)):
  summation = []
  for j in range(8):
    #print(j)
    #print(X_testPrediction[i][0][0])
    # print("First Predictor", X_testPrediction[i][j][0])
    # print("Second predictor", X_testPrediction[i][j][1])
    # print("Occurences",occurenceArray[j])
    summation.append(X_testPrediction[i][j][0] + X_testPrediction[i][j][1])
    
  #print(summation)
  if (np.argmax(summation)+2) == (y_testArray[i]//10):
    print("Sum is correct", np.argmax(summation)+2, y_testArray[i]//10)
    correct+=1
  elif ((np.argmax(summation)+3) == (y_testArray[i]//10)) or (np.argmax(summation)+1) == (y_testArray[i]//10):
    print("Sum is close", np.argmax(summation)+2, y_testArray[i]//10)
    close+=1
  elif ((np.argmax(summation)+4) == (y_testArray[i]//10)) or (np.argmax(summation)) == (y_testArray[i]//10):
    print("Sum is kinda close", np.argmax(summation)+2, y_testArray[i]//10)
    kindaClose+=1
  else:
    print("Sum is incorrect", "Predicted", np.argmax(summation)+2, "Actual", y_testArray[i]//10)

print("Percent correct", correct/len(X_testPrediction))
print("Percent close", (correct+close)/len(X_testPrediction))
print("Percent kinda close", (correct+close+kindaClose)/len(X_testPrediction))

  # print("Max occures in", np.argmax(summation) + 2)
  # print("Max should be", (y_testArray[i]//10))
  #Just gotta see if data is correct. Obviously it is not but maybe we can identify the errors.
  
  #print(summation + 1)
    

Sum is correct 7 7
Sum is correct 7 7
Sum is correct 7 7
Sum is correct 7 7
Sum is close 7 6
Sum is close 7 6
Sum is close 9 8
Sum is correct 7 7
Sum is incorrect Predicted 4 Actual 8
Sum is correct 6 6
Sum is correct 7 7
Sum is correct 9 9
Sum is correct 6 6
Sum is kinda close 8 6
Sum is close 7 8
Sum is kinda close 7 5
Sum is close 7 6
Sum is close 7 8
Sum is incorrect Predicted 4 Actual 7
Sum is close 7 8
Sum is correct 7 7
Sum is correct 7 7
Sum is kinda close 7 5
Sum is close 7 8
Sum is kinda close 7 9
Sum is correct 6 6
Sum is kinda close 7 9
Sum is kinda close 9 7
Sum is close 7 6
Sum is close 7 6
Sum is kinda close 7 5
Sum is correct 6 6
Sum is kinda close 3 5
Sum is correct 7 7
Sum is correct 7 7
Sum is kinda close 8 6
Sum is close 4 5
Sum is close 7 6
Sum is kinda close 9 7
Sum is correct 7 7
Sum is kinda close 7 9
Sum is kinda close 7 9
Sum is correct 6 6
Sum is kinda close 4 6
Sum is close 6 5
Sum is close 7 6
Sum is close 7 8
Sum is kinda close 4 6
Sum is kinda close 7 9
S