<a href="https://colab.research.google.com/github/itsTurner/ben-learns-ml/blob/main/GaussianDewPointPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If runtime ends then reimport

##Setting everything up

Import numpy and pandas

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import math



*Open* csv file with Pandas and format into arrays

In [ ]:
fullWeatherData = pd.read_csv('austin_weather.csv')
weatherData = fullWeatherData[['TempAvgF', 'DewPointAvgF', 'HumidityAvgPercent']]
shuffledWeatherData = weatherData.sample(frac=1)
X_train, X_test, y_train, y_test = train_test_split(shuffledWeatherData[['TempAvgF', 'HumidityAvgPercent']], shuffledWeatherData[['DewPointAvgF']], test_size=0.1, random_state=42)
X_trainArrayTemp = np.array(X_train['TempAvgF'])
X_trainArrayHumidity = np.array(X_train['HumidityAvgPercent'])
X_testArrayTemp = np.array(X_test['TempAvgF'])
X_testArrayHumidity = np.array(X_test['HumidityAvgPercent'])
y_trainArray = np.array(y_train['DewPointAvgF'])
y_testArray = np.array(y_test['DewPointAvgF'])
print(X_trainArrayTemp)
print(X_trainArrayHumidity)
print(X_testArrayTemp)
print(X_testArrayHumidity)
print(y_trainArray)
print(y_testArray)


[54 70 51 ... 34 89 83]
[67 83 63 ... 42 64 56]
[90 64 90 65 68 74 76 83 70 81 80 52 47 77 42 80 79 68 64 80 73 90 82 84
 74 33 39 89 75 70 62 85 55 67 75 76 50 78 89 73 70 67 71 57 63 84 64 62
 75 59 68 86 49 65 75 88 47 66 87 71 71 48 51 76 88 74 69 89 82 65 74 62
 91 83 83 84 65 88 59 38 93 79 51 61 89 79 66 51 82 57 59 76 68 80 64 49
 74 64 52 60 55 77 76 87 61 84 75 87 68 85 48 66 59 53 85 53 34 82 89 70
 63 56 64 68 88 86 43 54 87 67 89 75]
[59 59 60 70 86 79 78 72 60 67 55 95 59 61 76 77 56 90 70 55 68 59 61 73
 74 48 61 61 52 53 60 67 80 91 63 27 62 69 60 58 62 74 87 53 92 68 78 56
 56 58 75 54 92 74 83 62 44 71 69 72 57 59 66 61 66 83 74 59 52 49 67 38
 61 76 67 76 39 68 57 42 48 76 69 77 56 70 65 74 71 78 70 73 64 82 44 61
 87 67 97 43 52 73 70 75 48 70 74 62 85 64 58 68 82 52 73 42 76 73 67 74
 94 37 78 56 62 69 49 42 65 60 58 68]
[41 65 36 ... 12 72 62]
[71 47 71 53 64 65 68 72 52 66 57 49 32 60 37 72 59 65 51 61 61 71 64 72
 65 14 25 70 55 50 42 72 59 65 60 37 36 67 71 55 

##Process Data 
Sort Data, Get Mean, and get variance

Yes this might be easier to do but this was written at 11:00 PM and I no longer understand it

In [ ]:
tensSet = []
twentiesSet = []
thirtiesSet = []
fourtiesSet = []
fiftiesSet = []
sixtiesSet = []
seventiesSet = []
eightiesSet = []
ninetiesSet = []
for i in range(len(y_trainArray)):
  if y_trainArray[i] >= 8 and y_trainArray[i] <=19:
    tensSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif y_trainArray[i] > 19 and y_trainArray[i] <=29:
    twentiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif  y_trainArray[i] > 29 and y_trainArray[i] <=39:
    thirtiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif  y_trainArray[i] > 39 and y_trainArray[i] <=49:
    fourtiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif  y_trainArray[i] > 49 and y_trainArray[i] <=59:
    fiftiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif  y_trainArray[i] > 59 and y_trainArray[i] <=69:
    sixtiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  elif  y_trainArray[i] > 69 and y_trainArray[i] <=79:
    seventiesSet.append([X_trainArrayTemp[i], X_trainArrayHumidity[i], y_trainArray[i]])
  else:
    print(y_trainArray[i])
sortedSet = [tensSet, twentiesSet, thirtiesSet, fourtiesSet, fiftiesSet, sixtiesSet, seventiesSet]
print(tensSet)
print(twentiesSet)
print(thirtiesSet)
print(fourtiesSet)
print(fiftiesSet)
print(sixtiesSet)
print(seventiesSet)

print(sortedSet)

def mean(data, local):
  sum = 0
  for i in data:
    sum+=i[local]
  return sum/len(data)

meanArray = []
for i in range(len(sortedSet)):
  

  meanArray.append([mean(sortedSet[i], 0), mean(sortedSet[i], 1)])

def variance(data, local, mean):
  
  sum = 0
  for i in data:
    sum += (i[local] - mean[local])**2
  return sum/(len(data))
varianceArray = []

for i in range(len(sortedSet)):
  
  varianceArray.append([variance(sortedSet[i], 0, meanArray[i]), variance(sortedSet[i], 1, meanArray[i])])
  

for i in sortedSet:
  print(i)

for i in range(len(varianceArray)):
  print("Mean array", meanArray[i])
  print("Variance array",varianceArray[i])
  

  print(mean(sortedSet[i], 0))

[[32, 48, 12], [32, 48, 11], [30, 48, 12], [36, 43, 13], [38, 44, 17], [29, 55, 15], [37, 50, 18], [29, 54, 15], [33, 60, 17], [35, 43, 11], [34, 42, 12]]
[[34, 72, 25], [40, 60, 26], [39, 70, 29], [52, 35, 23], [45, 57, 29], [55, 40, 29], [46, 56, 28], [54, 31, 20], [48, 47, 26], [45, 52, 27], [52, 35, 26], [41, 54, 27], [56, 45, 29], [43, 51, 23], [58, 30, 22], [57, 40, 27], [50, 46, 27], [44, 50, 23], [47, 40, 20], [62, 28, 27], [52, 38, 23], [36, 62, 26], [53, 44, 28], [60, 51, 27], [55, 36, 26], [42, 61, 26], [47, 56, 29], [48, 47, 28], [45, 56, 27], [57, 41, 25], [42, 54, 23], [60, 36, 28], [41, 48, 24], [54, 45, 27], [49, 41, 25], [41, 54, 23], [35, 80, 29], [34, 84, 29], [45, 59, 27], [34, 68, 24], [42, 64, 29], [44, 55, 26], [42, 58, 28], [40, 60, 26], [51, 39, 23], [48, 53, 27], [46, 54, 28], [52, 39, 25], [36, 56, 20], [47, 49, 23], [40, 45, 20], [57, 43, 27], [34, 87, 29], [42, 52, 21], [56, 38, 27], [46, 56, 29], [45, 59, 28], [48, 48, 24], [49, 56, 29]]
[[51, 63, 36], [49

##Obtain Probability
Probability Function

In [ ]:

exampleArray = []
def probabilityArrayFunc(data, mean, variance):
  probArray = []
  for i in range(len(data)):
    probArray.append((1/(math.sqrt(2*math.pi*variance[i])))*math.exp(-1*((mean[i]-data[i])**2)/(2*variance[i])))
  return probArray


X_testPrediction = []

for j in range(len(X_testArrayHumidity)):
  tempArray = []
  for i in range(len(meanArray)):
    try:
      tempArray.append(np.log(probabilityArrayFunc([X_testArrayTemp[j], X_testArrayHumidity[j]], [meanArray[i][0], meanArray[i][1]], [varianceArray[i][0], varianceArray[i][1]])))
      #break
    except ValueError:
      print("Well this one had 0")      
  X_testPrediction.append(tempArray)
for i in X_testPrediction:
  print(i)


[array([-183.86583005,   -4.4074917 ]), array([-20.59907349,  -3.64428846]), array([-12.95344469,  -3.58709232]), array([-10.58372004,  -3.60536499]), array([-9.02372033, -3.68002048]), array([-4.58621268, -3.88721247]), array([-3.23592499, -4.04628444])]
[array([-55.51201255,  -4.4074917 ]), array([-5.70034374, -3.64428846]), array([-3.94799243, -3.58709232]), array([-3.10361902, -3.60536499]), array([-2.91078096, -3.68002048]), array([-4.82505765, -3.88721247]), array([-15.86664637,  -4.04628444])]
[array([-183.86583005,   -4.76901535]), array([-20.59907349,  -3.69910669]), array([-12.95344469,  -3.5921249 ]), array([-10.58372004,  -3.58267464]), array([-9.02372033, -3.61072235]), array([-4.58621268, -3.78301184]), array([-3.23592499, -3.86171465])]
[array([-59.04041106, -10.21455991]), array([-6.03595147, -4.60341544]), array([-4.11586223, -3.90757735]), array([-3.18112129, -3.64419071]), array([-2.84294547, -3.35166771]), array([-4.53734914, -3.25612087]), array([-14.57924046,  -2.

Final Step to Calculate what stuff should be

In [ ]:
correct = 0
close = 0
kindaClose = 0
for i in range(len(X_testPrediction)):
  summation = []
  for j in range(7):
    summation.append(X_testPrediction[i][j][0] + X_testPrediction[i][j][1])
    
  
  if (np.argmax(summation)+1) == (y_testArray[i]//10):
    #print("Sum is correct", np.argmax(summation)+1, y_testArray[i]//10)
    correct+=1
  elif ((np.argmax(summation)+2) == (y_testArray[i]//10)) or (np.argmax(summation)) == (y_testArray[i]//10):
    #print("Sum is close", np.argmax(summation)+1, y_testArray[i]//10)
    close+=1
  elif ((np.argmax(summation)+3) == (y_testArray[i]//10)):
    #print("Sum is kinda close", np.argmax(summation)+1, y_testArray[i]//10)
    kindaClose+=1
  #else:
    #print("Sum is incorrect", "Predicted", np.argmax(summation)+2, "Actual", y_testArray[i]//10)

print("Percent correct", correct/len(X_testPrediction))
print("Percent close", (correct+close)/len(X_testPrediction))
print("Percent kinda close", (correct+close+kindaClose)/len(X_testPrediction))


Percent correct 0.6893939393939394
Percent close 1.0
Percent kinda close 1.0
